insert into coin_list(coin_name)
values
    ('KRW-BTC'),
    ('KRW-BCH'),
    ('KRW-BCHA'),
    ('KRW-LTC'),
    ('KRW-ETC'),
    ('KRW-ADA'),
    ('KRW-SAND'),
    ('KRW-XRP'),
    ('KRW-XLM'),
    ('KRW-ETH'),
    ('KRW-TRX'),
    ('KRW-DOT'),
    ('KRW-LINK'),
    ('KRW-WAVES'),
    ('KRW-JST'),
    ('KRW-SXP'),
    ('KRW-META'),
    ('KRW-ICX'),
    ('KRW-ONT'),
    ('KRW-MED'),
    ('KRW-HUM'),
    ('KRW-THETA'),
    ('KRW-CHZ'),
    ('KRW-ENJ'),
    ('KRW-FLOW'),
    ('KRW-WAXP'),
    ('KRW-MANA'),
    ('KRW-EOS'),
    ('KRW-LSK'),
    ('KRW-ARK'),
    ('KRW-IOTA'),
    ('KRW-IOST'),
    ('KRW-XEM'),
    ('KRW-STRAX'),
    ('KRW-XTZ'),
    ('KRW-OMG'),
    ('KRW-SC'),
    ('KRW-GLM'),
    ('KRW-POWR'),
    ('KRW-CVC'),
    ('KRW-REP'),
    ('KRW-SBD'),
    ('KRW-ANKR'),
    ('KRW-PUNDIX'),
    ('KRW-MVL'),
    ('KRW-MLK'),
    ('KRW-NEO'),
    ('KRW-VET'),
    ('KRW-ELF');


insert into coin_theme(coin_name, coin_category)
values
('KRW-BTC', 'bitcoin'),
('KRW-BCH', 'bitcoin'),
('KRW-BCHA', 'bitcoin'),
('KRW-LTC', 'bitcoin'),
('KRW-ETC', 'ethereum'),
('KRW-ETH', 'ethereum'),
('KRW-ADA', 'ethereum'),
('KRW-SAND', 'ethereum'),
('KRW-XRP', 'ripple'),
('KRW-XLM', 'ripple'),
('KRW-ETH', 'defi'),
('KRW-TRX', 'defi'),
('KRW-DOT', 'defi'),
('KRW-LINK', 'defi'),
('KRW-WAVES', 'defi'),
('KRW-JST', 'defi'),
('KRW-SXP', 'defi'),
('KRW-META', 'did'),
('KRW-ICX', 'did'),
('KRW-ONT', 'did'),
('KRW-MED', 'did'),
('KRW-HUM', 'did'),
('KRW-THETA', 'nft'),
('KRW-CHZ', 'nft'),
('KRW-ENJ', 'nft'),
('KRW-FLOW', 'nft'),
('KRW-WAXP', 'nft'),
('KRW-MANA', 'nft'),
('KRW-EOS', 'platform'),
('KRW-WAVES', 'platform'),
('KRW-LSK', 'platform'),
('KRW-ARK', 'platform'),
('KRW-IOTA', 'platform'),
('KRW-IOST', 'platform'),
('KRW-XEM', 'platform'),
('KRW-STRAX', 'platform'),
('KRW-XTZ', 'platform'),
('KRW-OMG', 'utility'),
('KRW-SC', 'utility'),
('KRW-GLM', 'utility'),
('KRW-POWR', 'utility'),
('KRW-CVC', 'utility'),
('KRW-REP', 'utility'),
('KRW-WAXP', 'utility'),
('KRW-LINK', 'utility'),
('KRW-SBD', 'stable'),
('KRW-ANKR', 'stable'),
('KRW-PUNDIX', 'payment'),
('KRW-MVL', 'korea'),
('KRW-MLK', 'korea'),
('KRW-ICX', 'korea'),
('KRW-MED', 'korea'),
('KRW-NEO', 'china'),
('KRW-TRX', 'china'),
('KRW-ONT', 'china'),
('KRW-VET', 'china'),
('KRW-ELF', 'china'),
('KRW-XTZ', 'user-comb'),
('KRW-ELF', 'user-comb');
